# Natural Lang Processing(NLP) 자연어처리 

In [1]:
# 데이터 전처리 

# 1. Tokenization of Text

In [2]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [3]:
text = '해보지 않으면 해낼 수 없다'
result = text_to_word_sequence(text)
print(result)

['해보지', '않으면', '해낼', '수', '없다']


# Bag of Words

In [4]:
# 빈도수 

In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [6]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.', 
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.', 
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',]

In [7]:
token = Tokenizer()        # 토큰화 함수 지정
token.fit_on_texts(docs)   # 토큰화 함수에 문장 적용
print(token.word_counts)   # 단어의 빈도 수를 계산한 결과 출력


OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [8]:
print(token.document_count) # 문장의 개수 

3


In [9]:
print(token.word_docs)      
# 각 단어들이 몇개의 문장에 나오는지

defaultdict(<class 'int'>, {'단어를': 1, '텍스트의': 2, '각': 1, '토큰화합니다': 1, '먼저': 1, '나누어': 1, '토큰화해야': 1, '단어로': 1, '인식됩니다': 1, '딥러닝에서': 2, '토큰화한': 1, '수': 1, '결과는': 1, '사용할': 1, '있습니다': 1})


In [10]:
print(token.word_index)

{'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


# 2. One Hot Encoding of a Word
- 다중 분류

In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [12]:
text = '오랜동안 꿈꾸는 이는 그 꿈을 닮아간다'

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랜동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [13]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [14]:
# 0 ~ 6 정수 index => 0~1 배열로 
from keras.utils import to_categorical

# 인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) +1
x = to_categorical(x, num_classes=word_size)
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [15]:
# 오랫동안 [0. 1. 0. 0. 0. 0. 0.]
# 꿈구는   [0. 0. 1. 0. 0. 0. 0.]

# 3. Word Embedding
- one hot encoding = 벡터의 길이가 너무 길어짐 (쓸데없는 공간, 계산)
- 주어진 배열을 정해진 길이로 압축 
- eg. 16차원 => 4차원 벡터
- 오차 역전파 

In [16]:
from keras.layers import Embedding
from keras.models import Sequential

model = Sequential()
model.add(Embedding(16,4))
# 총 단어 수 16, 임베딩 후 출력되는 벡터 크기 4

# 4. Text 읽고 , 긍정 부정 예측

In [17]:
# 리뷰 => class 지정 : 긍정(1) 부정(0)

In [18]:
docs = ['너무 재밌네요','최고예요',
        '참 잘 만든 영화예요','추천하고 싶은 영화입니다.',
        '한 번 더 보고싶네요','글쎄요','별로예요',
        '생각보다 지루하네요','연기가 어색해요','재미없어요']

In [19]:
import numpy as np

classes = np.array([1,1,1,1,1,0,0,0,0,0])

In [20]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)   # 토큰화 된 결과를 출력해 확인

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [21]:
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]


# Padding
- 딥러닝 모델에 입력을 하려면 학습 데이터의 길이가 동일해야
- 길이를 똑같이 맞춰 주는 작업
- 원하는 길이보다 짧은 부분은 숫자 0을 넣어서 채워 
- 긴 데이터는 잘라서 같은 길이 
- 앞에서 생성한 x배열을 4개의 길이로

In [23]:
from keras.preprocessing.sequence import pad_sequences

padded_x = pad_sequences(x, 4)  
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


- 총 몇 개 index (입력), 
- 8개 embeddding 결과를 사용(출력), 
- padding 후, 4개 길이로 맞춰줌 => 매번 입력될 단어 수 4 (단어 수)

In [24]:
word_size = len(token.word_index) +1

In [25]:
# 단어 임베딩을 포함 & 딥러닝 모델 

from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D

model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [26]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              176       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 209
Trainable params: 209
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [30]:
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6841 - accuracy: 0.8000
Epoch 2/20
1/1 [==============================] - 0s 0s/step - loss: 0.6819 - accuracy: 0.9000
Epoch 3/20
1/1 [==============================] - 0s 999us/step - loss: 0.6797 - accuracy: 0.9000
Epoch 4/20
1/1 [==============================] - 0s 1000us/step - loss: 0.6776 - accuracy: 0.9000
Epoch 5/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6754 - accuracy: 0.9000
Epoch 6/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6732 - accuracy: 0.9000
Epoch 7/20
1/1 [==============================] - 0s 1000us/step - loss: 0.6710 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6688 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 1000us/step - loss: 0.6666 - accuracy: 1.0000
Epoch 10/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6644 - accuracy: 1.0000
Epoch 11/20
1/1 [============

In [33]:
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

1/1 [==============================] - 0s 1ms/step - loss: 0.6398 - accuracy: 1.0000

 Accuracy: 1.0000
